name: Monorepo Semantic Release
description: Apply semantic-release's automatic publishing to a monorepo
author: bubkoo <bubkoo.wy@gmail.com>

inputs:
  GITHUB_TOKEN:
    description: Your GitHub token for authentication
    required: true
  dryRun:
    description: |
      The objective of the dry-run mode is to get a preview of the pending
      release. Dry-run mode skips the following steps: `prepare`, `publish`,
      `success` and `fail`. In addition to this it prints the next version
      and release notes to the console.

      Note: The Dry-run mode verifies the repository push permission, even
      though nothing will be pushed. The verification is done to help user
      to figure out potential configuration issues.
  debug:
    description: Output debugging information
  sequential:
    description: Avoid hypothetical concurrent initialization collisions
  firstParent:
    description: Apply commit filtering to current branch only
  ignorePackages:
    description: |
      Packages list to be ignored on bumping process (append to the ones that
      already exist at `package.json` workspaces)
  ignorePrivatePackages:
    description: Private packages will be ignored
  deps_bump:
    description: |
      Define deps version update rule
        - `override` — replace any prev version with the next one.
        - `satisfy`  — check the next pkg version against its current
          references. If it matches (`*` matches to any, `1.1.0` matches
          `1.1.x`, `1.5.0` matches to `^1.0.0` and so on) release will not
          be triggered, if not `override` strategy will be applied instead.
        - `inherit` will try to follow the current declaration version/range.
          `~1.0.0` + `minor` turns into `~1.1.0`, `1.x` + `major` gives `2.x`,
          but `1.x` + `minor` gives `1.x` so there will be no release, etc.
  deps_prefix:
    description: |
      Optional prefix to be attached to the next version if `deps_bump` set to
      `override`. Supported values: `^` | `~` | `''`(empty string)
  deps_release:
    description: |
      Define release type for dependent package if any of its deps changes.
      `patch`, `minor`, `major` — strictly declare the release type that
      occurs when any dependency is updated; `inherit` — applies the "highest"
      release of updated deps to the package. For example, if any dep has a
      breaking change, `major` release will be applied to the all dependants
      up the chain.

runs:
  using: node12
  main: dist/index.js

branding:
  icon: send
  color: green
